version: '3'

services:

  tasklogger_db:
    image: mysql:5.7.32
    container_name: tasklogger_db
    restart: unless-stopped
    ports:
      - "3306:3306"
      - "3307:3307"
    environment:
      MYSQL_DATABASE:  tasklogger_db
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: tasklogger_db
    volumes:
      - dbdata:/var/lib/mysql/

volumes:
  dbdata:
    driver: local
