version: '3'
services:
  
  # MySql Service
  db:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: phyton_database
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAEM: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf 

  # Phyton Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app
    depends_on:
      - db
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: mydb
      DB_USER: myuser
      DB_PASSWORD: mypassword

volumes:
  dbdata:
